name: Java CI
on: [push]

jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Jenkinsfile
        uses: jenkinsci/jenkinsfile-runner-github-actions@v0
        with:
          jenkinsfile: Jenkinsfile
          plugins: plugins.txt
